### PR TITLE
adding LINE svg icon

### PR DESCRIPTION
**Pull request by skatkov**
This should resolve - #47

I've tried svgo with zero effect
svgcleaner made this svg unusable

so I rolled back and did all changes I could manually.

### CODE REVIEW

**Comment by edent** [comment]
Looks great! Thanks :-)

**Comment by edent** [comment]
Sorry, just seen this is `2077` bytes. That's too big for us.

**Comment by RazrFalcon** [comment]
@edent it's easy to shrink it below 1k. Will do this on weekends.

**Comment by RazrFalcon** [comment]
@skatkov 

>I've tried svgo with zero effect
svgcleaner made this svg unusable

They can't help in path nodes removing. It can only be done manually.

**Pull request merged**
